### ISSUE TITLE
Configuration import error from old kdb-stduio

### ISSUE THREAD

**Issue by Yanpas** [dzmipt/kdbStudio#89]
Stack trace:
```
2021.08.13 14:34:34.178 [main] INFO  studio.kdb.Config - Found old config. Converting...
2021.08.13 14:34:34.204 [main] ERROR studio.kdb.Config - Ups... Can't convert
java.lang.IllegalArgumentException: Server with full name XXXXX already exists
        at studio.kdb.Config.addServerInternal(Config.java:648) ~[main/:?]
        at studio.kdb.Config.addServers(Config.java:694) ~[main/:?]
        at studio.kdb.Config.upgradeTo12(Config.java:264) ~[main/:?]
        at studio.kdb.Config.checkForUpgrade(Config.java:283) ~[main/:?]
        at studio.kdb.Config.init(Config.java:238) ~[main/:?]
        at studio.kdb.Config.<init>(Config.java:57) ~[main/:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) [?:?]
        at studio.kdb.Config.getInstance(Config.java:214) [main/:?]
        at studio.kdb.Config.getInstance(Config.java:210) [main/:?]
        at studio.core.Studio.main(Studio.java:49) [main/:?]
2021.08.13 14:34:34.383 [AWT-EventQueue-0] INFO  studio.core.Studio - Start Studio with args []

```

In the outcome previous studio.properties are lost forever

**Comment by Yanpas** [comment]
That helps:
```diff
diff --git a/src/studio/kdb/Config.java b/src/studio/kdb/Config.java
index 67609af..415e83a 100755
--- a/src/studio/kdb/Config.java
+++ b/src/studio/kdb/Config.java
@@ -645,7 +645,8 @@ public class Config {
         String name = server.getName();
         String fullName = server.getFullName();
         if (serverNames.contains(fullName)) {
-            throw new IllegalArgumentException("Server with full name " + fullName + " already exists");
+            // throw new IllegalArgumentException("Server with full name " + fullName + " already exists");
+            return;
         }
         if (name.trim().length() == 0) {
             throw new IllegalArgumentException("Server name can't be empty");
```

**Comment by dzmipt** [comment]
@Yanpas, Sorry, that I didn't response for long time... I thought that GitHub would notify owner of a repository about a new issues raised.

As for the issue... Based on the stacktrace it looks that you had duplicate server name in old configuration (for some reason). And the Studio started without any servers. I think i fixed conversion. If it is possible to check on your side (if the old config file left), it would be great.

**Comment by Yanpas** [comment]
Thanks, this fixed the issue.

I've inspected old studio properties file, it has duplicates entries in `Servers` property. Like `Servers=A,B,C,B,B`
